hawtio:
  authenticationEnabled: false
management:
  endpoints:
    web:
      exposure:
        include: hawtio,jolokia
server:
  port: 8081
spring:
  activemq:
    close-timeout: 15
    in-memory: true
  application:
    name: activemq-sender